export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CLEARGRAD_VALUES = 'CLEARGRAD_VALUES'


export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const CREATE_GRAD_BEGIN = 'CREATE_GRAD_BEGIN'
export const CREATE_GRAD_SUCCESS = 'CREATE_GRAD_SUCCESS'
export const CREATE_GRAD_ERROR = 'CREATE_GRAD_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const GET_GRADS_BEGIN = 'GET_GRAD_BEGIN'
export const GET_GRADS_SUCCESS = 'GET_GRAD_SUCCESS'

export const GET_ALLGRADS_BEGIN = 'GET_ALLGRADS_BEGIN'
export const GET_ALLGRADS_SUCCESS = 'GET_ALLGRADS_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const SET_EDIT_GRAD = 'SET_EDIT_GRAD'

export const UPDATE_EDIT_GRAD_JUSTIFICATIVA = 'UPDATE_EDIT_GRAD_JUSTIFICATIVA'

export const DELETE_JOB_BEGIN = 'DELETE_GRAD_BEGIN'

export const DELETE_GRAD_BEGIN = 'DELETE_GRAD_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const EDIT_GRAD_BEGIN = 'EDIT_GRAD_BEGIN'
export const EDIT_GRAD_SUCCESS = 'EDIT_GRAD_SUCCESS'
export const EDIT_GRAD_ERROR = 'EDIT_GRAD_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const GET_EGRESSO_PROFILE_BEGIN = 'GET_EGRESSO_PROFILE_BEGIN'
export const GET_EGRESSO_PROFILE_SUCCESS = 'GET_EGRESSO_PROFILE_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CLEAR_USERFILTERS = 'CLEAR_USERFILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'